// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: proto/vector.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Vector              `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorRequest) Reset() {
	*x = VectorRequest{}
	mi := &file_proto_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRequest) ProtoMessage() {}

func (x *VectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRequest.ProtoReflect.Descriptor instead.
func (*VectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_vector_proto_rawDescGZIP(), []int{0}
}

func (x *VectorRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_proto_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_proto_vector_proto_rawDescGZIP(), []int{1}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type VectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Vector                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorResponse) Reset() {
	*x = VectorResponse{}
	mi := &file_proto_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorResponse) ProtoMessage() {}

func (x *VectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorResponse.ProtoReflect.Descriptor instead.
func (*VectorResponse) Descriptor() ([]byte, []int) {
	return file_proto_vector_proto_rawDescGZIP(), []int{2}
}

func (x *VectorResponse) GetResult() *Vector {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VectorResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_vector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vector_proto_rawDescGZIP(), []int{3}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reputation    float32                `protobuf:"fixed32,2,opt,name=reputation,proto3" json:"reputation,omitempty"`
	CorrectSums   int32                  `protobuf:"varint,3,opt,name=correct_sums,json=correctSums,proto3" json:"correct_sums,omitempty"`
	IncorrectSums int32                  `protobuf:"varint,4,opt,name=incorrect_sums,json=incorrectSums,proto3" json:"incorrect_sums,omitempty"`
	Crashes       int32                  `protobuf:"varint,5,opt,name=crashes,proto3" json:"crashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_vector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vector_proto_rawDescGZIP(), []int{4}
}

func (x *StatsResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StatsResponse) GetReputation() float32 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

func (x *StatsResponse) GetCorrectSums() int32 {
	if x != nil {
		return x.CorrectSums
	}
	return 0
}

func (x *StatsResponse) GetIncorrectSums() int32 {
	if x != nil {
		return x.IncorrectSums
	}
	return 0
}

func (x *StatsResponse) GetCrashes() int32 {
	if x != nil {
		return x.Crashes
	}
	return 0
}

var File_proto_vector_proto protoreflect.FileDescriptor

const file_proto_vector_proto_rawDesc = "" +
	"\n" +
	"\x12proto/vector.proto\x12\x06vector\"9\n" +
	"\rVectorRequest\x12(\n" +
	"\avectors\x18\x01 \x03(\v2\x0e.vector.VectorR\avectors\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"Q\n" +
	"\x0eVectorResponse\x12&\n" +
	"\x06result\x18\x01 \x01(\v2\x0e.vector.VectorR\x06result\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\"\x0e\n" +
	"\fStatsRequest\"\xac\x01\n" +
	"\rStatsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1e\n" +
	"\n" +
	"reputation\x18\x02 \x01(\x02R\n" +
	"reputation\x12!\n" +
	"\fcorrect_sums\x18\x03 \x01(\x05R\vcorrectSums\x12%\n" +
	"\x0eincorrect_sums\x18\x04 \x01(\x05R\rincorrectSums\x12\x18\n" +
	"\acrashes\x18\x05 \x01(\x05R\acrashes2\x85\x01\n" +
	"\rVectorService\x12;\n" +
	"\n" +
	"SumVectors\x12\x15.vector.VectorRequest\x1a\x16.vector.VectorResponse\x127\n" +
	"\bGetStats\x12\x14.vector.StatsRequest\x1a\x15.vector.StatsResponseB\x16Z\x14vector-sum-system/pbb\x06proto3"

var (
	file_proto_vector_proto_rawDescOnce sync.Once
	file_proto_vector_proto_rawDescData []byte
)

func file_proto_vector_proto_rawDescGZIP() []byte {
	file_proto_vector_proto_rawDescOnce.Do(func() {
		file_proto_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vector_proto_rawDesc), len(file_proto_vector_proto_rawDesc)))
	})
	return file_proto_vector_proto_rawDescData
}

var file_proto_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_vector_proto_goTypes = []any{
	(*VectorRequest)(nil),  // 0: vector.VectorRequest
	(*Vector)(nil),         // 1: vector.Vector
	(*VectorResponse)(nil), // 2: vector.VectorResponse
	(*StatsRequest)(nil),   // 3: vector.StatsRequest
	(*StatsResponse)(nil),  // 4: vector.StatsResponse
}
var file_proto_vector_proto_depIdxs = []int32{
	1, // 0: vector.VectorRequest.vectors:type_name -> vector.Vector
	1, // 1: vector.VectorResponse.result:type_name -> vector.Vector
	0, // 2: vector.VectorService.SumVectors:input_type -> vector.VectorRequest
	3, // 3: vector.VectorService.GetStats:input_type -> vector.StatsRequest
	2, // 4: vector.VectorService.SumVectors:output_type -> vector.VectorResponse
	4, // 5: vector.VectorService.GetStats:output_type -> vector.StatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vector_proto_init() }
func file_proto_vector_proto_init() {
	if File_proto_vector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vector_proto_rawDesc), len(file_proto_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vector_proto_goTypes,
		DependencyIndexes: file_proto_vector_proto_depIdxs,
		MessageInfos:      file_proto_vector_proto_msgTypes,
	}.Build()
	File_proto_vector_proto = out.File
	file_proto_vector_proto_goTypes = nil
	file_proto_vector_proto_depIdxs = nil
}
